/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public abstract class CallbackPath {
  private int call(long path, int type){
    charArray jpath = new charArray(path,false);
    tiledb_object_t jtype = tiledb_object_t.swigToEnum(type);
    return call(ArrayUtils.charArrayGet(jpath),jtype);
  }

  public abstract int call(String path, tiledb_object_t type);
}
