/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public class tiledb_ctx_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tiledb_ctx_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tiledb_ctx_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_tiledb_ctx_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStorage_manager_(SWIGTYPE_p_tiledb__StorageManager value) {
    tiledbJNI.tiledb_ctx_t_storage_manager__set(swigCPtr, this, SWIGTYPE_p_tiledb__StorageManager.getCPtr(value));
  }

  public SWIGTYPE_p_tiledb__StorageManager getStorage_manager_() {
    long cPtr = tiledbJNI.tiledb_ctx_t_storage_manager__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb__StorageManager(cPtr, false);
  }

  public void setLast_error_(SWIGTYPE_p_tiledb__Status value) {
    tiledbJNI.tiledb_ctx_t_last_error__set(swigCPtr, this, SWIGTYPE_p_tiledb__Status.getCPtr(value));
  }

  public SWIGTYPE_p_tiledb__Status getLast_error_() {
    long cPtr = tiledbJNI.tiledb_ctx_t_last_error__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb__Status(cPtr, false);
  }

  public void setMtx_(SWIGTYPE_p_std__mutex value) {
    tiledbJNI.tiledb_ctx_t_mtx__set(swigCPtr, this, SWIGTYPE_p_std__mutex.getCPtr(value));
  }

  public SWIGTYPE_p_std__mutex getMtx_() {
    long cPtr = tiledbJNI.tiledb_ctx_t_mtx__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mutex(cPtr, false);
  }

  public tiledb_ctx_t() {
    this(tiledbJNI.new_tiledb_ctx_t(), true);
  }

}
