/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public class tiledb_config_iter_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tiledb_config_iter_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tiledb_config_iter_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_tiledb_config_iter_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParam_values_(SWIGTYPE_p_std__mapT_std__string_std__string_t value) {
    tiledbJNI.tiledb_config_iter_t_param_values__set(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getParam_values_() {
    long cPtr = tiledbJNI.tiledb_config_iter_t_param_values__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_std__string_std__string_t(cPtr, false);
  }

  public void setIt_(SWIGTYPE_p_std__mapT_std__string_std__string_t__iterator value) {
    tiledbJNI.tiledb_config_iter_t_it__set(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_t__iterator.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t__iterator getIt_() {
    long cPtr = tiledbJNI.tiledb_config_iter_t_it__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_std__string_std__string_t__iterator(cPtr, false);
  }

  public tiledb_config_iter_t() {
    this(tiledbJNI.new_tiledb_config_iter_t(), true);
  }

}
