/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public class tiledb_array_schema_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tiledb_array_schema_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tiledb_array_schema_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_tiledb_array_schema_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArray_schema_(SWIGTYPE_p_tiledb__ArraySchema value) {
    tiledbJNI.tiledb_array_schema_t_array_schema__set(swigCPtr, this, SWIGTYPE_p_tiledb__ArraySchema.getCPtr(value));
  }

  public SWIGTYPE_p_tiledb__ArraySchema getArray_schema_() {
    long cPtr = tiledbJNI.tiledb_array_schema_t_array_schema__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb__ArraySchema(cPtr, false);
  }

  public tiledb_array_schema_t() {
    this(tiledbJNI.new_tiledb_array_schema_t(), true);
  }

}
